---
#- name: Run the equivalent of "apt-get update" as a separate step
#  apt:
#    update_cache: yes
- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - graftnode
- name: Run graftnode
  service: 
    name: graftnode 
    state: started

