---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
- name: Install a list of packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - graftnode 
    - graft-supernode
- name: Run supernode
  shell: "(GRAFTNET=`grep GRAFT_NETWORK /etc/default/graft | awk -F'=' '{print $2}'` && perl -pi -e  's/wallet-public-address=/wallet-public-address='${GRAFTNET}'/g' /etc/graft/supernode-config.ini)"
  async: 10
  poll: 0
